"""empty message

Revision ID: 009e7cc2e004
Revises: 3a43ec7622dc
Create Date: 2023-05-21 09:28:52.457956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '009e7cc2e004'
down_revision = '3a43ec7622dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('horse', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('horse', schema=None) as batch_op:
        batch_op.drop_column('img')

    # ### end Alembic commands ###
