"""empty message

Revision ID: 613fd5b27b54
Revises: 
Create Date: 2023-05-08 09:56:55.827070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '613fd5b27b54'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ganadería',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('horse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=1000), nullable=False),
    sa.Column('fecha_nacimiento', sa.String(length=1000), nullable=False),
    sa.Column('ganaderia', sa.String(length=1000), nullable=False),
    sa.Column('sexo', sa.String(length=1000), nullable=False),
    sa.Column('precio', sa.Integer(), nullable=False),
    sa.Column('capa', sa.String(length=1000), nullable=False),
    sa.Column('alzada', sa.String(length=1000), nullable=False),
    sa.Column('provincia', sa.String(length=1000), nullable=False),
    sa.Column('nivel_doma', sa.String(length=1000), nullable=False),
    sa.Column('descripcion', sa.String(length=1000), nullable=False),
    sa.Column('imagenes', sa.String(length=1000), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=250), nullable=True),
    sa.Column('horse_id', sa.Integer(), nullable=True),
    sa.Column('user_owner_id', sa.Integer(), nullable=True),
    sa.Column('user_interested_id', sa.Integer(), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['horse_id'], ['horse.id'], ),
    sa.ForeignKeyConstraint(['user_interested_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    op.drop_table('horse')
    op.drop_table('user')
    op.drop_table('ganadería')
    # ### end Alembic commands ###
