"""empty message

Revision ID: 63f724b22d1a
Revises: 
Create Date: 2023-04-27 19:24:19.722379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63f724b22d1a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('horse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=1000), nullable=False),
    sa.Column('fecha_nacimiento', sa.String(length=1000), nullable=False),
    sa.Column('ganaderia', sa.String(length=1000), nullable=False),
    sa.Column('sexo', sa.String(length=1000), nullable=False),
    sa.Column('precio', sa.Integer(), nullable=False),
    sa.Column('capa', sa.String(length=1000), nullable=False),
    sa.Column('alzada', sa.String(length=1000), nullable=False),
    sa.Column('provincia', sa.String(length=1000), nullable=False),
    sa.Column('nivel_doma', sa.String(length=1000), nullable=False),
    sa.Column('descripcion', sa.String(length=1000), nullable=False),
    sa.Column('imagenes', sa.String(length=1000), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_text', sa.String(length=250), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    op.drop_table('post')
    op.drop_table('horse')
    op.drop_table('user')
    # ### end Alembic commands ###
