"""empty message

Revision ID: 846bbf3c0955
Revises: 88185c39e88a
Create Date: 2023-04-28 09:37:01.460559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '846bbf3c0955'
down_revision = '88185c39e88a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('horse', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('dueño')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_name_key', ['name'])

    with op.batch_alter_table('horse', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dueño', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
