"""empty message

Revision ID: 88185c39e88a
Revises: 
Create Date: 2023-04-22 10:46:03.217148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88185c39e88a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('horse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=1000), nullable=False),
    sa.Column('fecha_nacimiento', sa.String(length=1000), nullable=False),
    sa.Column('ganaderia', sa.String(length=1000), nullable=False),
    sa.Column('sexo', sa.String(length=1000), nullable=False),
    sa.Column('precio', sa.Integer(), nullable=False),
    sa.Column('capa', sa.String(length=1000), nullable=False),
    sa.Column('alzada', sa.String(length=1000), nullable=False),
    sa.Column('provincia', sa.String(length=1000), nullable=False),
    sa.Column('nivel_doma', sa.String(length=1000), nullable=False),
    sa.Column('descripcion', sa.String(length=1000), nullable=False),
    sa.Column('imagenes', sa.String(length=1000), nullable=False),
    sa.Column('dueño', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('horse')
    # ### end Alembic commands ###
